const SEARCH_PHOTOS_URL = "https://happy-cori-e2a104.netlify.app/search";

// ☝️ Types generated by Copilot. Could import the types from somewhere? 
export interface PhotoSearchResponse {
    page: number;
    per_page: number;
    photos: Photo[];
    total_results: number;
    next_page?: string;
}

export interface Photo {
    id: number;
    width: number;
    height: number;
    url: string;
    photographer: string;
    photographer_url: string;
    photographer_id: number;
    avg_color: string;
    src: PhotoSrc;
    liked: boolean;
    alt: string;
}

export interface PhotoSrc {
    original: string;
    large2x: string;
    large: string;
    medium: string;
    small: string;
    portrait: string;
    landscape: string;
    tiny: string;
}


export async function fetchPhotos(query: string): Promise<PhotoSearchResponse> {

    // 💬
    // Uncomment this to demonstrate a bug
    // Then, in the actual application, type 'mel' and then a delay, and then 'b'
    // What you will see is that the 'mel' query will clobber the 'melb' query.
    // if (query === "mel") {
    //     await new Promise(resolve => setTimeout(resolve, 2000)); // Simulate a delay for "mel"
    // }

    const response = await fetch(`${SEARCH_PHOTOS_URL}?` + new URLSearchParams({ query }));
    // Check if the response is ok (status in the range 200-299)
    if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
    }
    const result = await response.json();
    // 💬 Could validate the response shape here. 
    return result;
}