<script setup lang="ts">
import { defineEmits } from 'vue';

const SEARCH_PHOTOS_URL = "https://happy-cori-e2a104.netlify.app/search";

// ☝️ Types generated by Copilot. Could import the types from somewhere? 
export interface PhotoSearchResponse {
    page: number;
    per_page: number;
    photos: Photo[];
    total_results: number;
    next_page?: string;
}

export interface Photo {
    id: number;
    width: number;
    height: number;
    url: string;
    photographer: string;
    photographer_url: string;
    photographer_id: number;
    avg_color: string;
    src: PhotoSrc;
    liked: boolean;
    alt: string;
}

export interface PhotoSrc {
    original: string;
    large2x: string;
    large: string;
    medium: string;
    small: string;
    portrait: string;
    landscape: string;
    tiny: string;
}


async function fetchPhotos(query: string): Promise<PhotoSearchResponse | null> {
    try {
        const response = await fetch(`${SEARCH_PHOTOS_URL}?` + new URLSearchParams({ query }));
        // Check if the response is ok (status in the range 200-299)
        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }
        const result = await response.json();
        // 💬 Could validate the response shape here. 
        return result;
    } catch (error) {

        // 💬 Bit of a question about how we want to handle errors. 
        // I'm thinking that blowing up the application is not needed. 
        // Could display a toast like message I think. 
        // So would dispatch one from here.
        console.error('Error fetching data:', error);
        return null;
    }
}
// Define the props for the component


// Define an emit event to send the input value to the parent component
const emit = defineEmits(['updateSearchQuery']);

const handleInput = async (event: Event) => {
    // 🧑‍🔬 I don't like having to manually specify the the change event/element types. 
    // In react if we inline the change handler, the types are inferred.
    const target = event.currentTarget as HTMLInputElement;
    const searchResult = await fetchPhotos(target.value);;
    emit('updateSearchQuery', searchResult);
};
</script>

<template>
    <div>
        <input type="text" placeholder="Search photos..." @input="handleInput" />
    </div>
</template>

<style scoped></style>
